### ISSUE TITLE
Why are TLS ciphers not configured by using "crypto/tls/fipsonly"

### ISSUE THREAD

**Issue by dlipovetsky** [igor-kupczynski/fips-echo-server#1]
Thanks very much for the helpful example project, and your blog post!

I'm wondering why you configure the TLS ciphers by hand manually: https://github.com/igor-kupczynski/fips-echo-server/blob/329753ea31c8cac82b457317b79d43d6440fc43e/main.go#L63

From what I understand, you can get FIPS-compliant TLS by importing the "crypto/tls/fipsonly" package, as described [here](https://github.com/golang/go/blob/go1.19.3/src/crypto/tls/fipsonly/fipsonly.go).

**Comment by igor-kupczynski** [comment]
Neat, thanks for sharing. I guess there's no good reason to configure the ciphers manually. I'll read up on `"crypto/tls/fipsonly" package` and update the repo.

**Comment by igor-kupczynski** [comment]
Hey @dlipovetsky,

Looking at the [`"crypto/tls/fipsonly"` package](https://github.com/golang/go/blob/go1.19.3/src/crypto/tls/fipsonly/fipsonly.go) I think the main difference between "manual" configuration is that it can happen at runtime (in my example `-fipsMode="true"` flag), while `import _ "crypto/tls/fipsonly"` happens at build time. This means that you can't provide a single binary for your FIPS and non-FIPS usecases.

I will highlight that in the README and the blogpost, because if you don't have non-FIPS usecases then this seems simpler, with less room for error (and indeed, take a look at https://github.com/igor-kupczynski/fips-echo-server/issues/2).

Thanks again for reporting!

**Comment by igor-kupczynski** [comment]
Added a note in the blogpost https://kupczynski.info/posts/fips-golang/#force-fips-compliant-crypto-at-compile-time

Thanks again for bringing that up!
